// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_users.sql

package sqlcdb

import (
	"context"
)

const listActivePasscodeHashes = `-- name: ListActivePasscodeHashes :many
SELECT passcode_hash FROM telive.host_users WHERE active = TRUE
`

func (q *Queries) ListActivePasscodeHashes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActivePasscodeHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var passcode_hash string
		if err := rows.Scan(&passcode_hash); err != nil {
			return nil, err
		}
		items = append(items, passcode_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
