// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type TeliveEntrySong struct {
	ID        int32
	EntryID   int
	SongID    int
	Performed bool
	SortOrder int
}

type TeliveHostUser struct {
	ID           int32
	Label        string
	PasscodeHash string
	Active       bool
}

type TelivePerformedSong struct {
	ID          int32
	Singer      string
	SongID      int
	PerformedAt time.Time
}

type TeliveSetting struct {
	Key   string
	Value string
}

type TeliveSignup struct {
	ID           int32
	Name         string
	Position     float64
	TimesOnStage int
	CreatedAt    time.Time
}

type TeliveSong struct {
	ID     int32
	Title  string
	Artist string
	TabUrl sql.NullString
}
