// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performed_songs.sql

package sqlcdb

import (
	"context"
)

const listPerformedToday = `-- name: ListPerformedToday :many
SELECT ps.singer, s.id, s.title, s.artist, COALESCE(s.tab_url, '') AS tab_url
FROM telive.performed_songs ps
JOIN telive.songs s ON s.id = ps.song_id
WHERE ps.performed_at >= CURRENT_DATE
ORDER BY ps.performed_at ASC
`

type ListPerformedTodayRow struct {
	Singer string
	ID     int32
	Title  string
	Artist string
	TabUrl string
}

func (q *Queries) ListPerformedToday(ctx context.Context) ([]ListPerformedTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, listPerformedToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerformedTodayRow
	for rows.Next() {
		var i ListPerformedTodayRow
		if err := rows.Scan(
			&i.Singer,
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.TabUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
