// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcdb

import (
	"context"
)

const getSignupsOpen = `-- name: GetSignupsOpen :one
SELECT value FROM telive.settings WHERE key = 'signups_open'
`

func (q *Queries) GetSignupsOpen(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSignupsOpen)
	var value string
	err := row.Scan(&value)
	return value, err
}
