// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signups.sql

package sqlcdb

import (
	"context"
)

const hasName = `-- name: HasName :one
SELECT EXISTS(
    SELECT 1 FROM telive.signups
    WHERE LOWER(name) = LOWER($1)
      AND created_at >= CURRENT_DATE
) AS exists
`

func (q *Queries) HasName(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasName, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
