// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signups.sql

package sqlcdb

import (
	"context"
)

const hasName = `-- name: HasName :one
SELECT EXISTS(
    SELECT 1 FROM telive.signups
    WHERE LOWER(name) = LOWER($1)
      AND created_at >= CURRENT_DATE
) AS exists
`

func (q *Queries) HasName(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasName, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTodayPositions = `-- name: ListTodayPositions :many
SELECT id, position FROM telive.signups
WHERE created_at >= CURRENT_DATE
ORDER BY position ASC
`

type ListTodayPositionsRow struct {
	ID       int32
	Position float64
}

func (q *Queries) ListTodayPositions(ctx context.Context) ([]ListTodayPositionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodayPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodayPositionsRow
	for rows.Next() {
		var i ListTodayPositionsRow
		if err := rows.Scan(&i.ID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
