// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package sqlcdb

import (
	"context"
)

const listSongs = `-- name: ListSongs :many
SELECT id, title, artist, COALESCE(tab_url, '') AS tab_url
FROM telive.songs
ORDER BY title ASC
`

type ListSongsRow struct {
	ID     int32
	Title  string
	Artist string
	TabUrl string
}

func (q *Queries) ListSongs(ctx context.Context) ([]ListSongsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsRow
	for rows.Next() {
		var i ListSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.TabUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
