--liquibase formatted sql

--changeset dan:5
INSERT INTO songs (title, artist, tab_url) VALUES
    ('9 to 5', 'Dolly Parton', 'https://ultimate-guitar.com'),
    ('A-Punk', 'Vampire Weekend', 'https://ultimate-guitar.com'),
    ('ABC', 'The Jackson 5', 'https://ultimate-guitar.com'),
    ('Ain''t It Fun', 'Paramore', 'https://ultimate-guitar.com'),
    ('Ain''t No Mountain High Enough', 'Marvin Gaye, Tammi Terrell', 'https://ultimate-guitar.com'),
    ('Ain''t No Rest for the Wicked', 'Cage The Elephant', 'https://ultimate-guitar.com'),
    ('Alive', 'Pearl Jam', 'https://ultimate-guitar.com'),
    ('All Apologies', 'Nirvana', 'https://ultimate-guitar.com'),
    ('All Star', 'Smash Mouth', 'https://ultimate-guitar.com'),
    ('all the good girls go to hell', 'Billie Eilish', 'https://ultimate-guitar.com'),
    ('All The Small Things', 'blink-182', 'https://ultimate-guitar.com'),
    ('Alone', 'Heart', 'https://ultimate-guitar.com'),
    ('American Girl', 'Tom Petty and the Heartbreakers', 'https://ultimate-guitar.com'),
    ('Another Brick in the Wall, Pt. 2', 'Pink Floyd', 'https://ultimate-guitar.com'),
    ('Anti-Hero', 'Taylor Swift', 'https://ultimate-guitar.com'),
    ('Are You Gonna Be My Girl', 'Jet', 'https://ultimate-guitar.com'),
    ('Baba O''Riley', 'The Who', 'https://ultimate-guitar.com'),
    ('Baby', 'Justin Bieber, Ludacris', 'https://ultimate-guitar.com'),
    ('Baby Got Back', 'Sir Mix-A-Lot', 'https://ultimate-guitar.com'),
    ('Back In Black', 'AC/DC', 'https://ultimate-guitar.com'),
    ('bad guy', 'Billie Eilish', 'https://ultimate-guitar.com'),
    ('Bad Romance', 'Lady Gaga', 'https://ultimate-guitar.com'),
    ('Banditos', 'The Refreshments', 'https://ultimate-guitar.com'),
    ('Barracuda', 'Heart', 'https://ultimate-guitar.com'),
    ('Basket Case', 'Green Day', 'https://ultimate-guitar.com'),
    ('Beat It', 'Michael Jackson', 'https://ultimate-guitar.com'),
    ('Before He Cheats', 'Carrie Underwood', 'https://ultimate-guitar.com'),
    ('Bennie And The Jets', 'Elton John', 'https://ultimate-guitar.com'),
    ('Beverly Hills', 'Weezer', 'https://ultimate-guitar.com'),
    ('Billie Jean', 'Michael Jackson', 'https://ultimate-guitar.com'),
    ('Blister In The Sun', 'Violent Femmes', 'https://ultimate-guitar.com'),
    ('Bohemian Rhapsody', 'Queen', 'https://tabs.ultimate-guitar.com/tab/queen/bohemian-rhapsody-chords-40606'),
    ('Born to Run', 'Bruce Springsteen', 'https://ultimate-guitar.com'),
    ('Brain Stew', 'Green Day', 'https://ultimate-guitar.com'),
    ('Brown Eyed Girl', 'Van Morrison', 'https://ultimate-guitar.com'),
    ('Buddy Holly', 'Weezer', 'https://ultimate-guitar.com'),
    ('Bulls On Parade', 'Rage Against The Machine', 'https://ultimate-guitar.com'),
    ('Burning Down the House', 'Talking Heads', 'https://ultimate-guitar.com'),
    ('Bust A Move', 'Young MC', 'https://ultimate-guitar.com'),
    ('Cake by the Ocean', 'DNCE', 'https://ultimate-guitar.com'),
    ('California Dreamin''', 'The Mamas & The Papas', 'https://ultimate-guitar.com'),
    ('California Gurls', 'Katy Perry, Snoop Dogg', 'https://ultimate-guitar.com'),
    ('Californication', 'Red Hot Chili Peppers', 'https://ultimate-guitar.com'),
    ('Call Me Maybe', 'Carly Rae Jepsen', 'https://ultimate-guitar.com'),
    ('Can''t Get Enough Of Your Love, Babe', 'Barry White', 'https://ultimate-guitar.com'),
    ('Can''t Hardly Wait', 'The Replacements', 'https://ultimate-guitar.com'),
    ('Can''t Help Falling in Love', 'Elvis Presley', 'https://ultimate-guitar.com'),
    ('Chop Suey!', 'System Of A Down', 'https://ultimate-guitar.com'),
    ('Cigarette Daydreams', 'Cage The Elephant', 'https://ultimate-guitar.com'),
    ('Come As You Are', 'Nirvana', 'https://ultimate-guitar.com'),
    ('Come Together', 'The Beatles', 'https://ultimate-guitar.com'),
    ('Comfortably Numb', 'Pink Floyd', 'https://ultimate-guitar.com'),
    ('Complicated', 'Avril Lavigne', 'https://ultimate-guitar.com'),
    ('Crazy In Love (feat. Jay-Z)', 'Beyoncé, JAY-Z', 'https://ultimate-guitar.com'),
    ('Crazy Little Thing Called Love', 'Queen', 'https://ultimate-guitar.com'),
    ('Crazy On You', 'Heart', 'https://ultimate-guitar.com'),
    ('Crazy Train', 'Ozzy Osbourne', 'https://ultimate-guitar.com'),
    ('Creep', 'Radiohead', 'https://ultimate-guitar.com'),
    ('Criminal', 'Fiona Apple', 'https://ultimate-guitar.com'),
    ('Crocodile Rock', 'Elton John', 'https://ultimate-guitar.com'),
    ('Cryin''', 'Aerosmith', 'https://ultimate-guitar.com'),
    ('Cult of Personality', 'Living Colour', 'https://ultimate-guitar.com'),
    ('Dancing Queen', 'ABBA', 'https://ultimate-guitar.com'),
    ('Dani California', 'Red Hot Chili Peppers', 'https://ultimate-guitar.com'),
    ('Dirty Work', 'Steely Dan', 'https://ultimate-guitar.com'),
    ('Doctor My Eyes', 'Jackson Browne', 'https://ultimate-guitar.com'),
    ('Don''t Look Back In Anger', 'Oasis', 'https://ultimate-guitar.com'),
    ('Don''t Speak', 'No Doubt', 'https://ultimate-guitar.com'),
    ('Don''t Stop Believin''', 'Journey', 'https://ultimate-guitar.com'),
    ('Don''t You (Forget About Me)', 'Simple Minds', 'https://ultimate-guitar.com'),
    ('Dream A Little Dream Of Me', 'The Mamas & The Papas', 'https://ultimate-guitar.com'),
    ('Dream On', 'Aerosmith', 'https://ultimate-guitar.com'),
    ('Easy', 'Commodores', 'https://ultimate-guitar.com'),
    ('End Of The Road', 'Boyz II Men', 'https://ultimate-guitar.com'),
    ('Enter Sandman', 'Metallica', 'https://ultimate-guitar.com'),
    ('Everlong', 'Foo Fighters', 'https://ultimate-guitar.com'),
    ('Everybody Talks', 'Neon Trees', 'https://ultimate-guitar.com'),
    ('Ex''s & Oh''s', 'Elle King', 'https://ultimate-guitar.com'),
    ('Eye of the Tiger', 'Survivor', 'https://ultimate-guitar.com'),
    ('Faithfully', 'Journey', 'https://ultimate-guitar.com'),
    ('Fight For Your Right', 'Beastie Boys', 'https://ultimate-guitar.com'),
    ('Fire', 'Jimi Hendrix', 'https://ultimate-guitar.com'),
    ('Firework', 'Katy Perry', 'https://ultimate-guitar.com'),
    ('Flagpole Sitta', 'Harvey Danger', 'https://ultimate-guitar.com'),
    ('Flowers', 'Miley Cyrus', 'https://ultimate-guitar.com'),
    ('Folsom Prison Blues', 'Johnny Cash', 'https://ultimate-guitar.com'),
    ('Foxey Lady', 'Jimi Hendrix', 'https://ultimate-guitar.com'),
    ('Free Fallin''', 'Tom Petty', 'https://ultimate-guitar.com'),
    ('Friends in Low Places', 'Garth Brooks', 'https://ultimate-guitar.com'),
    ('Gimme Shelter', 'The Rolling Stones', 'https://ultimate-guitar.com'),
    ('Girl Crush', 'Little Big Town', 'https://ultimate-guitar.com'),
    ('Girl on Fire', 'Alicia Keys', 'https://ultimate-guitar.com'),
    ('Girls & Boys', 'Blur', 'https://ultimate-guitar.com'),
    ('Girls Just Want to Have Fun', 'Cyndi Lauper', 'https://ultimate-guitar.com'),
    ('Gives You Hell', 'The All-American Rejects', 'https://ultimate-guitar.com'),
    ('Glory Days', 'Bruce Springsteen', 'https://ultimate-guitar.com'),
    ('good 4 u', 'Olivia Rodrigo', 'https://ultimate-guitar.com'),
    ('Good Riddance (Time of Your Life)', 'Green Day', 'https://ultimate-guitar.com'),
    ('Grenade', 'Bruno Mars', 'https://ultimate-guitar.com'),
    ('Happy', 'Pharrell Williams', 'https://ultimate-guitar.com'),
    ('Heat Waves', 'Glass Animals', 'https://ultimate-guitar.com'),
    ('Hello', 'Adele', 'https://ultimate-guitar.com'),
    ('Hey Jude', 'The Beatles', 'https://ultimate-guitar.com'),
    ('Hey There Delilah', 'Plain White T''s', 'https://ultimate-guitar.com'),
    ('High and Dry', 'Radiohead', 'https://ultimate-guitar.com'),
    ('Highway to Hell', 'AC/DC', 'https://ultimate-guitar.com'),
    ('Hips Don''t Lie', 'Shakira', 'https://ultimate-guitar.com'),
    ('Hit Me With Your Best Shot', 'Pat Benatar', 'https://ultimate-guitar.com'),
    ('Holiday', 'Green Day', 'https://ultimate-guitar.com'),
    ('House Of The Rising Sun', 'The Animals', 'https://ultimate-guitar.com'),
    ('How Sweet It Is (To Be Loved By You)', 'Marvin Gaye', 'https://ultimate-guitar.com'),
    ('Hungry Like the Wolf', 'Duran Duran', 'https://ultimate-guitar.com'),
    ('I Believe in a Thing Called Love', 'The Darkness', 'https://ultimate-guitar.com'),
    ('I Feel the Earth Move', 'Carole King', 'https://ultimate-guitar.com'),
    ('I Heard It Through The Grapevine', 'Marvin Gaye', 'https://ultimate-guitar.com'),
    ('I Wanna Be Sedated', 'Ramones', 'https://ultimate-guitar.com'),
    ('I Wanna Dance with Somebody', 'Whitney Houston', 'https://ultimate-guitar.com'),
    ('I Want It That Way', 'Backstreet Boys', 'https://ultimate-guitar.com'),
    ('I Want To Hold Your Hand', 'The Beatles', 'https://ultimate-guitar.com'),
    ('I Want You Back', 'The Jackson 5', 'https://ultimate-guitar.com'),
    ('I Will Survive - Single Version', 'Gloria Gaynor', 'https://ultimate-guitar.com'),
    ('I Wish', 'Skee-Lo', 'https://ultimate-guitar.com'),
    ('I''m a Believer', 'The Monkees', 'https://ultimate-guitar.com'),
    ('I''m Gonna Be (500 Miles)', 'The Proclaimers', 'https://ultimate-guitar.com'),
    ('I''m So Excited', 'The Pointer Sisters', 'https://ultimate-guitar.com'),
    ('If It Makes You Happy', 'Sheryl Crow', 'https://ultimate-guitar.com'),
    ('Immigrant Song', 'Led Zeppelin', 'https://ultimate-guitar.com'),
    ('Interstate Love Song', 'Stone Temple Pilots', 'https://ultimate-guitar.com'),
    ('Iron Man', 'Black Sabbath', 'https://ultimate-guitar.com'),
    ('Ironic', 'Alanis Morissette', 'https://ultimate-guitar.com'),
    ('Irreplaceable', 'Beyoncé', 'https://ultimate-guitar.com'),
    ('Is This Love', 'Bob Marley & The Wailers', 'https://ultimate-guitar.com'),
    ('Island In The Sun', 'Weezer', 'https://ultimate-guitar.com'),
    ('It''s Raining Men', 'The Weather Girls', 'https://ultimate-guitar.com'),
    ('It''s Too Late', 'Carole King', 'https://ultimate-guitar.com'),
    ('Jamming', 'Bob Marley & The Wailers', 'https://ultimate-guitar.com'),
    ('Jeremy', 'Pearl Jam', 'https://ultimate-guitar.com'),
    ('Jolene', 'Dolly Parton', 'https://ultimate-guitar.com'),
    ('Jump', 'Van Halen', 'https://ultimate-guitar.com'),
    ('Just a Friend', 'Biz Markie', 'https://ultimate-guitar.com'),
    ('Just A Girl', 'No Doubt', 'https://ultimate-guitar.com'),
    ('Karma Police', 'Radiohead', 'https://ultimate-guitar.com'),
    ('Killing Me Softly With His Song', 'Fugees, Ms. Lauryn Hill', 'https://ultimate-guitar.com'),
    ('Kiss', 'Prince', 'https://ultimate-guitar.com'),
    ('Last Nite', 'The Strokes', 'https://ultimate-guitar.com'),
    ('Lean on Me', 'Bill Withers', 'https://ultimate-guitar.com'),
    ('Learn to Fly', 'Foo Fighters', 'https://ultimate-guitar.com'),
    ('Let It Be', 'The Beatles', 'https://ultimate-guitar.com'),
    ('Let''s Get It On', 'Marvin Gaye', 'https://ultimate-guitar.com'),
    ('Life During Wartime', 'Talking Heads', 'https://ultimate-guitar.com'),
    ('Life is a Highway', 'Rascal Flatts', 'https://ultimate-guitar.com'),
    ('Lithium', 'Nirvana', 'https://ultimate-guitar.com'),
    ('Little Red Corvette', 'Prince', 'https://ultimate-guitar.com'),
    ('Livin'' On A Prayer', 'Bon Jovi', 'https://ultimate-guitar.com'),
    ('Locked out of Heaven', 'Bruno Mars', 'https://ultimate-guitar.com'),
    ('London Calling', 'The Clash', 'https://ultimate-guitar.com'),
    ('Lost on You', 'LP', 'https://ultimate-guitar.com'),
    ('Love Rollercoaster', 'Ohio Players', 'https://ultimate-guitar.com'),
    ('Love Shack', 'The B-52''s', 'https://ultimate-guitar.com'),
    ('Love Story', 'Taylor Swift', 'https://ultimate-guitar.com'),
    ('Love Yourself', 'Justin Bieber', 'https://ultimate-guitar.com'),
    ('Lovely Day', 'Bill Withers', 'https://ultimate-guitar.com'),
    ('Man, I Feel Like a Woman', 'Shania Twain', 'https://ultimate-guitar.com'),
    ('Man in the Box', 'Alice In Chains', 'https://ultimate-guitar.com'),
    ('Mary Jane''s Last Dance', 'Tom Petty and the Heartbreakers', 'https://ultimate-guitar.com'),
    ('Me and Julio Down by the Schoolyard', 'Paul Simon', 'https://ultimate-guitar.com'),
    ('Message In A Bottle', 'The Police', 'https://ultimate-guitar.com'),
    ('Misery Business', 'Paramore', 'https://ultimate-guitar.com'),
    ('Moonage Daydream', 'David Bowie', 'https://ultimate-guitar.com'),
    ('Movin'' Out (Anthony''s Song)', 'Billy Joel', 'https://ultimate-guitar.com'),
    ('Mr. Brightside', 'The Killers', 'https://ultimate-guitar.com'),
    ('Ms. Jackson', 'Outkast', 'https://ultimate-guitar.com'),
    ('Mustang Sally', 'Wilson Pickett', 'https://ultimate-guitar.com'),
    ('My Girl', 'The Temptations', 'https://ultimate-guitar.com'),
    ('My Hero', 'Foo Fighters', 'https://ultimate-guitar.com'),
    ('My Own Worst Enemy', 'Lit', 'https://ultimate-guitar.com'),
    ('My Way', 'Frank Sinatra', 'https://ultimate-guitar.com'),
    ('Nineteen Seventy-Nine (1979)', 'The Smashing Pumpkins', 'https://ultimate-guitar.com'),
    ('No Rain', 'Blind Melon', 'https://ultimate-guitar.com'),
    ('No Scrubs', 'TLC', 'https://ultimate-guitar.com'),
    ('Nothing Else Matters', 'Metallica', 'https://ultimate-guitar.com'),
    ('Oh, Pretty Woman', 'Roy Orbison', 'https://ultimate-guitar.com'),
    ('Only Girl (In The World)', 'Rihanna', 'https://ultimate-guitar.com'),
    ('Only the Good Die Young', 'Billy Joel', 'https://ultimate-guitar.com'),
    ('Paint It, Black', 'The Rolling Stones', 'https://ultimate-guitar.com'),
    ('Paradise City', 'Guns N'' Roses', 'https://ultimate-guitar.com'),
    ('Paranoid', 'Black Sabbath', 'https://ultimate-guitar.com'),
    ('Party In The U.S.A.', 'Miley Cyrus', 'https://ultimate-guitar.com'),
    ('People Are Strange', 'The Doors', 'https://ultimate-guitar.com'),
    ('Piano Man', 'Billy Joel', 'https://ultimate-guitar.com'),
    ('Piece of My Heart', 'Big Brother & The Holding Company', 'https://ultimate-guitar.com'),
    ('Pinball Wizard', 'The Who', 'https://ultimate-guitar.com'),
    ('Pink Pony Club', 'Chappell Roan', 'https://ultimate-guitar.com'),
    ('Play That Funky Music', 'Wild Cherry', 'https://ultimate-guitar.com'),
    ('Please, Please, Please', 'Sabrina Carpenter', 'https://ultimate-guitar.com'),
    ('Plush', 'Stone Temple Pilots', 'https://ultimate-guitar.com'),
    ('Poison', 'Bell Biv DeVoe', 'https://ultimate-guitar.com'),
    ('Poker Face', 'Lady Gaga', 'https://ultimate-guitar.com'),
    ('Possum Kingdom', 'Toadies', 'https://ultimate-guitar.com'),
    ('Pour Some Sugar On Me', 'Def Leppard', 'https://ultimate-guitar.com'),
    ('Psycho Killer', 'Talking Heads', 'https://ultimate-guitar.com'),
    ('Purple Haze', 'Jimi Hendrix', 'https://ultimate-guitar.com'),
    ('Purple Rain', 'Prince', 'https://ultimate-guitar.com'),
    ('Raise Your Glass', 'P!nk', 'https://ultimate-guitar.com'),
    ('Rebel Yell', 'Billy Idol', 'https://ultimate-guitar.com'),
    ('Rehab', 'Amy Winehouse', 'https://ultimate-guitar.com'),
    ('Rescue Me', 'Fontella Bass', 'https://ultimate-guitar.com'),
    ('Respect', 'Aretha Franklin', 'https://ultimate-guitar.com'),
    ('Return of the Mack', 'Mark Morrison', 'https://ultimate-guitar.com'),
    ('Ring of Fire', 'Johnny Cash', 'https://ultimate-guitar.com'),
    ('Rock and Roll', 'Led Zeppelin', 'https://ultimate-guitar.com'),
    ('Rock with You', 'Michael Jackson', 'https://ultimate-guitar.com'),
    ('Rocket Man', 'Elton John', 'https://ultimate-guitar.com'),
    ('Rolling in the Deep', 'Adele', 'https://ultimate-guitar.com'),
    ('Rooster', 'Alice In Chains', 'https://ultimate-guitar.com'),
    ('Roxanne', 'The Police', 'https://ultimate-guitar.com'),
    ('Runnin'' Down A Dream', 'Tom Petty', 'https://ultimate-guitar.com'),
    ('Santeria', 'Sublime', 'https://ultimate-guitar.com'),
    ('Satisfaction', 'The Rolling Stones', 'https://ultimate-guitar.com'),
    ('Say It Ain''t So', 'Weezer', 'https://ultimate-guitar.com'),
    ('Scotty Doesn''t Know', 'Lustra', 'https://ultimate-guitar.com'),
    ('Semi-Charmed Life', 'Third Eye Blind', 'https://ultimate-guitar.com'),
    ('Separate Ways (Worlds Apart)', 'Journey', 'https://ultimate-guitar.com'),
    ('September', 'Earth, Wind & Fire', 'https://ultimate-guitar.com'),
    ('Seven Nation Army', 'The White Stripes', 'https://ultimate-guitar.com'),
    ('Sex & Candy', 'Marcy Playground', 'https://ultimate-guitar.com'),
    ('Sex on Fire', 'Kings of Leon', 'https://ultimate-guitar.com'),
    ('Shake It Off', 'Taylor Swift', 'https://ultimate-guitar.com'),
    ('Shallow', 'Lady Gaga', 'https://ultimate-guitar.com'),
    ('Should I Stay or Should I Go', 'The Clash', 'https://ultimate-guitar.com'),
    ('Shut Up and Dance', 'WALK THE MOON', 'https://ultimate-guitar.com'),
    ('Since U Been Gone', 'Kelly Clarkson', 'https://ultimate-guitar.com'),
    ('Sittin'' On The Dock of the Bay', 'Otis Redding', 'https://ultimate-guitar.com'),
    ('Sledgehammer', 'Peter Gabriel', 'https://ultimate-guitar.com'),
    ('Smells Like Teen Spirit', 'Nirvana', 'https://ultimate-guitar.com'),
    ('So What', 'P!nk', 'https://ultimate-guitar.com'),
    ('Some Nights', 'fun.', 'https://ultimate-guitar.com'),
    ('Son of a Preacher Man', 'Dusty Springfield', 'https://ultimate-guitar.com'),
    ('Song 2', 'Blur', 'https://ultimate-guitar.com'),
    ('Space Oddity', 'David Bowie', 'https://ultimate-guitar.com'),
    ('Stand By Me', 'Ben E. King', 'https://ultimate-guitar.com'),
    ('Start Me Up', 'The Rolling Stones', 'https://ultimate-guitar.com'),
    ('Stayin'' Alive', 'Bee Gees', 'https://ultimate-guitar.com'),
    ('Still into You', 'Paramore', 'https://ultimate-guitar.com'),
    ('Sugar, We''re Goin Down', 'Fall Out Boy', 'https://ultimate-guitar.com'),
    ('Summer Nights', 'Grease', 'https://ultimate-guitar.com'),
    ('Sunshine Of Your Love', 'Cream', 'https://ultimate-guitar.com'),
    ('Supersonic', 'Oasis', 'https://ultimate-guitar.com'),
    ('Superstition', 'Stevie Wonder', 'https://ultimate-guitar.com'),
    ('Surrender', 'Cheap Trick', 'https://ultimate-guitar.com'),
    ('Sweet Child O'' Mine', 'Guns N'' Roses', 'https://ultimate-guitar.com'),
    ('Sweet Emotion', 'Aerosmith', 'https://ultimate-guitar.com'),
    ('Sweet Jane', 'The Velvet Underground', 'https://ultimate-guitar.com'),
    ('T.N.T.', 'AC/DC', 'https://ultimate-guitar.com'),
    ('Tainted Love', 'Soft Cell', 'https://ultimate-guitar.com'),
    ('Take Me Out', 'Franz Ferdinand', 'https://ultimate-guitar.com'),
    ('Take Me to Church', 'Hozier', 'https://ultimate-guitar.com'),
    ('Teenage Dirtbag', 'Wheatus', 'https://ultimate-guitar.com'),
    ('Tennessee Whiskey', 'Chris Stapleton', 'https://ultimate-guitar.com'),
    ('Tequila', 'Dan and Shay', 'https://ultimate-guitar.com'),
    ('Thank You', 'Dido', 'https://ultimate-guitar.com'),
    ('The Distance', 'CAKE', 'https://ultimate-guitar.com'),
    ('The Lazy Song', 'Bruno Mars', 'https://ultimate-guitar.com'),
    ('The Middle', 'Jimmy Eat World', 'https://ultimate-guitar.com'),
    ('The Weight', 'The Band', 'https://ultimate-guitar.com'),
    ('Three Little Birds', 'Bob Marley & The Wailers', 'https://ultimate-guitar.com'),
    ('Thriller', 'Michael Jackson', 'https://ultimate-guitar.com'),
    ('Tighten Up', 'The Black Keys', 'https://ultimate-guitar.com'),
    ('Time After Time', 'Cyndi Lauper', 'https://ultimate-guitar.com'),
    ('Tiny Dancer', 'Elton John', 'https://ultimate-guitar.com'),
    ('Torn', 'Natalie Imbruglia', 'https://ultimate-guitar.com'),
    ('Tubthumping', 'Chumbawamba', 'https://ultimate-guitar.com'),
    ('Turn the Beat Around', 'Vicki Sue Robinson', 'https://ultimate-guitar.com'),
    ('Twist And Shout', 'The Beatles', 'https://ultimate-guitar.com'),
    ('Umbrella', 'Rihanna, JAY-Z', 'https://ultimate-guitar.com'),
    ('Under the Bridge', 'Red Hot Chili Peppers', 'https://ultimate-guitar.com'),
    ('Uptown Funk', 'Bruno Mars', 'https://ultimate-guitar.com'),
    ('Use Somebody', 'Kings of Leon', 'https://ultimate-guitar.com'),
    ('Valerie', 'Amy Winehouse', 'https://ultimate-guitar.com'),
    ('Wagon Wheel', 'Darius Rucker', 'https://ultimate-guitar.com'),
    ('Wake Me Up When September Ends', 'Green Day', 'https://ultimate-guitar.com'),
    ('Walk Like an Egyptian', 'The Bangles', 'https://ultimate-guitar.com'),
    ('Walk This Way', 'Aerosmith', 'https://ultimate-guitar.com'),
    ('Wannabe', 'Spice Girls', 'https://ultimate-guitar.com'),
    ('Watching The Detectives', 'Elvis Costello', 'https://ultimate-guitar.com'),
    ('We Are The Champions', 'Queen', 'https://ultimate-guitar.com'),
    ('We Are Young', 'fun., Janelle Monáe', 'https://ultimate-guitar.com'),
    ('We Didn''t Start the Fire', 'Billy Joel', 'https://ultimate-guitar.com'),
    ('We Will Rock You', 'Queen', 'https://ultimate-guitar.com'),
    ('What A Wonderful World', 'Louis Armstrong', 'https://ultimate-guitar.com'),
    ('What I Got', 'Sublime', 'https://ultimate-guitar.com'),
    ('What''s My Age Again?', 'blink-182', 'https://ultimate-guitar.com'),
    ('What''s So Funny ''Bout Peace, Love….', 'Elvis Costello & The Attractions', 'https://ultimate-guitar.com'),
    ('What''s Up?', '4 Non Blondes', 'https://ultimate-guitar.com'),
    ('When Doves Cry', 'Prince', 'https://ultimate-guitar.com'),
    ('When I Come Around', 'Green Day', 'https://ultimate-guitar.com'),
    ('When We Were Young', 'Adele', 'https://ultimate-guitar.com'),
    ('Where Is My Mind?', 'Pixies', 'https://ultimate-guitar.com'),
    ('Where You Lead', 'Carole King', 'https://ultimate-guitar.com'),
    ('Whip It', 'DEVO', 'https://ultimate-guitar.com'),
    ('White Rabbit', 'Jefferson Airplane', 'https://ultimate-guitar.com'),
    ('White Wedding - Pt. 1', 'Billy Idol', 'https://ultimate-guitar.com'),
    ('Whitehouse Road', 'Tyler Childers', 'https://ultimate-guitar.com'),
    ('Wild World', 'Yusuf / Cat Stevens', 'https://ultimate-guitar.com'),
    ('Wonderwall', 'Oasis', 'https://ultimate-guitar.com'),
    ('Wrecking Ball', 'Miley Cyrus', 'https://ultimate-guitar.com'),
    ('YMCA', 'Village People', 'https://ultimate-guitar.com'),
    ('You Belong With Me', 'Taylor Swift', 'https://ultimate-guitar.com'),
    ('You Can''t Always Get What You Want', 'The Rolling Stones', 'https://ultimate-guitar.com'),
    ('You Oughta Know', 'Alanis Morissette', 'https://ultimate-guitar.com'),
    ('You''re My Best Friend', 'Queen', 'https://ultimate-guitar.com'),
    ('Young Americans', 'David Bowie', 'https://ultimate-guitar.com'),
    ('Ziggy Stardust', 'David Bowie', 'https://ultimate-guitar.com'),
    ('Zombie', 'The Cranberries', 'https://ultimate-guitar.com')
;
